### ISSUE TITLE
Empty TextGrids cause import to fail

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/PolyglotDB#145]
Right now if any of the TextGrids are empty, then the import process fails since no types can be extracted from it. The parser should probably just skip over such files. This was an issue for the cleaned version of AudioBNC

**Comment by msonderegger** [comment]
That sounds right. Could you do? Thanks.

On Thu, Jun 20, 2019 at 4:30 PM Michael Goodale <notifications@github.com<mailto:notifications@github.com>> wrote:

Right now if any of the TextGrids are empty, then the import process fails since no types can be extracted from it. The parser should probably just skip over such files.
